baseURL = "https://www.kitllog.com/"
languageCode = "ja"
title = "kit_lifelog"
theme = "hugo-kiera"
copyright = "Copyright &copy; 2021 - kit887"

paginate = 5
summaryLength = 60
#canonifyurls = true # 相対パスではなく baseurl を基点とした絶対パスにする
hasCJKLanguage = true
enableEmoji = true
pygmentsCodeFences = true
#pygmentsstyle = "solarizedlight"
#PygmentsOptions = "linenos=table,nobackground=true"
#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line

[author]
    name = "kit887"
    github = "kit887"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = "kit_887"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[params]
    tagline = "おんなじこと何度もぐぐりたくない"
    description = "おんなじことを何度も検索しない未来を目指して作ったライフログです。"
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = ["/css/custom.css"]  #Optional Customised CSS
    favicon = "/images/favicon_io/favicon-32x32.png"
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    #katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

# uncomment to enable the Tags link on the main toolbar
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 1

# uncomment to enable the Categories link on the main toolbar
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 1
